Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace 历史人物可视化.Controllers
{
    public class AboutController : Controller
    {
        // GET: About
        public ActionResult Index()
        {
            return View();
        }
    }
}

Controllers/DisplayController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using MongoDB.Bson;
using MongoDB.Driver;
using 历史人物可视化.Models;


namespace 历史人物可视化.Controllers
{
    public class DisplayController : Controller
    {
        const int page_size = 16; //每页展示人数
        const int p_len = 80;     //人物简介字数
        List<BsonDocument> documents = new List<BsonDocument>();
        Dictionary<string, object> relation_dic = new Dictionary<string, object>();

        #region

        /// <summary>
        /// 无返回值检索
        /// </summary>
        /// <param name="DB_name"></param>
        /// <param name="collection_name"></param>
        /// <param name="filter"></param>
        public void GetBsonDocument(string DB_name, string collection_name, FilterDefinition<BsonDocument> filter, string entity_name="", bool is_first=false, int flag=0)
        {
            var client = new MongoClient("mongodb://localhost:27017");
            var database = client.GetDatabase(DB_name);
            var collection = database.GetCollection<BsonDocument>(collection_name);

            var sort = Builders<BsonDocument>.Sort.Descending("Heat");
            var projection = Builders<BsonDocument>.Projection.Exclude("_id");

            var cursor = collection.Find(filter).Project(projection).Sort(sort).ToCursor();
            foreach (var document in cursor.ToEnumerable())
            {
                if (!is_first)
                {
                    if (!relation_dic.ContainsKey(document["Name"].ToString()) && document["Name"].ToString() != entity_name)
                        documents.Add(document);
                    if (flag == 1)
                        relation_dic.Add(document["Name"].ToString(), document["Relation"][entity_name][0].ToString().Split(' '));
                }
                else
                {
                    documents.Add(document);
                }
            }
        }

        /// <summary>
        /// 有返回值检索
        /// </summary>
        /// <param name="DB_name"></param>
        /// <param name="collection_name"></param>
        /// <param name="filter"></param>
        /// <returns>List<BsonDocument></returns>
        public List<BsonDocument> Get_BsonDocuments(string DB_name, string collection_name, FilterDefinition<BsonDocument> filter)
        {
            List<BsonDocument> documents = new List<BsonDocument>();
            var client = new MongoClient("mongodb://localhost:27017");
            var database = client.GetDatabase(DB_name);
            var collection = database.GetCollection<BsonDocument>(collection_name);

            var sort = Builders<BsonDocument>.Sort.Descending("Heat");
            var projection = Builders<BsonDocument>.Projection.Exclude("_id");

            var cursor = collection.Find(filter).Project(projection).Sort(sort).ToCursor();
            foreach (var document in cursor.ToEnumerable())
            {
                documents.Add(document);
            }
            return documents;
        }

        /// <summary>
        /// 人物知识图谱动态加载数据
        /// </summary>
        /// <param name="name"></param>
        /// <param name="tag"></param>
        /// <returns></returns>
        public JsonResult Mongo(string name, string tag)
        {
            List<BsonDocument> rela_documents;
            Dictionary<string, object> dic = new Dictionary<string, object>();
            if (tag == "PER")
            {
                var filter = Builders<BsonDocument>.Filter.Eq("Name", name);
                rela_documents = Get_BsonDocuments("figures", "Person2_copy", filter);

                if (rela_documents.Count > 0)
                    dic = rela_documents[0]["Relation"].AsBsonDocument.ToDictionary();
            }
            else
            {
                var filter = Builders<BsonDocument>.Filter.Exists("Relation." + name, true);
                rela_documents = Get_BsonDocuments("figures", "Person2_copy", filter);
                if (rela_documents.Count > 0)
                {
                    foreach (BsonDocument document in rela_documents)
                    {
                        List<string> rela = new List<string>();
                        rela.Add(document["Relation"][name][0].ToString());
                        rela.Add("PER");
                        dic.Add(document["Name"].ToString(), rela);
                    }
                }
            }

            return Json(dic, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 获取人物足迹地点字典
        /// </summary>
        /// <param name="name"></param>
        /// <returns></returns>
        public JsonResult GetPlace(string name)
        {
            Dictionary<string, object> place_count = new Dictionary<string, object>();
            var filter = Builders<BsonDocument>.Filter.Eq("Name", name);
            GetBsonDocument("figures", "Person2_copy", filter);
            var Path = documents[0]["Biography1"].AsBsonArray;
            foreach (var path in Path)
            {
                if (path["Coord"].AsBsonArray.Count > 1)
                {
                    foreach(var coord in path["Coord"].AsBsonArray)
                    {
                        string key = coord[0].ToString() + ',' + coord[1].ToString();
                        if (place_count.ContainsKey(key))
                        {
                            int isCoint = Int32.Parse(place_count[key].ToString());
                            place_count[key] = isCoint + 1;
                        }
                        else
                            place_count.Add(key, 1);
                    }
                }
            }
            return Json(place_count, JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region
        /// <summary>
        /// 人物检索页
        /// </summary>
        /// <param name="page"></param>
        /// <returns></returns>
        public ActionResult Search(string entity_name, int page)
        {
            List<Entity> e = new List<Entity>();

            if (documents.Count == 0)
            {
                //全部检索
                if (entity_name == "all")
                {
                    GetBsonDocument("figures", "Person2_copy", new BsonDocument());
                }

                //特定查询
                else
                {
                    //Step1.获取人名
                    var filter = Builders<BsonDocument>.Filter.Eq("Name", entity_name);
                    GetBsonDocument("figures", "Person2_copy", filter, entity_name, true, 0);

                    //Step2.获取人物关系
                    filter = Builders<BsonDocument>.Filter.Exists("Relation." + entity_name, true);
                    GetBsonDocument("figures", "Person2_copy", filter, entity_name, false, 1);

                    //Step3.获取关键词
                    filter = Builders<BsonDocument>.Filter.In("Keyword.Word", new[] { entity_name });
                    GetBsonDocument("figures", "Person2_copy", filter, entity_name, false, 0);
                }
            }

            if (documents.Count > 0)
            {
                ViewBag.Count = Math.Ceiling(Convert.ToDouble(documents.Count) / page_size);

                int start_index = (page - 1) * 16;
                for (int i = start_index; i < start_index + 16; i++)
                {
                    if (i < documents.Count)
                    {
                        Entity peo = new Entity();
                        peo.Name = documents[i]["Name"].ToString();
                        try
                        {
                            string[] s = documents[i]["Introduction"].AsBsonArray[0].ToString().Split('。');
                            if (s[0].Length > p_len)
                            {
                                s[0] = s[0].Substring(0, p_len);
                                int index = s[0].LastIndexOf('，');
                                s[0] = s[0].Substring(0, index);
                            }
                            s[0] += '。';
                            peo.Introduction.Add(s[0]);

                        }
                        catch { peo.Introduction.Add("暂无人物描述"); }
                        e.Add(peo);
                    }
                    else
                        break;
                }
                ViewBag.Entity = e;
                ViewBag.Relation = relation_dic;
                ViewBag.Total = e.Count;
            }
            else
            {
                ViewBag.Count = 0;
                ViewBag.Total = 0;
            }

            ViewBag.Page = page;
            ViewBag.Search = entity_name;

            return View();
        }

        /// <summary>
        /// 人物信息页
        /// </summary>
        /// <param name="name"></param>
        /// <returns></returns>
        public ActionResult Detail(string name)
        {
            var filter = Builders<BsonDocument>.Filter.Eq("Name", name);
            List<BsonDocument> detail_list = Get_BsonDocuments("figures", "Person2_copy", filter);
            if (detail_list.Count > 0)
            {
                ViewBag.People = detail_list[0];
                return View();
            }
            else
            {
                return View("~/Views/Display/Search.cshtml");
            }
        }

        /// <summary>
        /// 人物知识图谱
        /// </summary>
        /// <param name="name"></param>
        /// <returns></returns>
        public ActionResult About(string name)
        {
            var filter = Builders<BsonDocument>.Filter.Eq("Name", name);
            GetBsonDocument("figures", "Person2_copy", filter);
            ViewBag.Relation = documents[0]["Relation"];
            ViewBag.Name = documents[0]["Name"];

Views/Display/Search.cshtml
@{
    ViewBag.Title = "风云人物";
}

@section styles{
    <link href="~/Content/search.css" rel="stylesheet" />
}

    <!-- 检索页面内容 -->
    <div class="container" style="min-height:39rem">
        <!-- 搜索栏 -->
        <div class="row">
            <div class="col-md-12">
                <div class="content search-box">
                    <input class="input-number" id="input-number" value="" placeholder="输入人名、机构、地名等关键词以查询相关人物" />
                    <div class="search" id="peo-search"><span class="glyphicon glyphicon-search" aria-hidden="true" style="padding-bottom:5px;"></span>&nbsp&nbsp搜索</div>
                </div>
            </div>
        </div>


        <!-- 人物信息 -->
        @{
        if (ViewBag.Total > 0)
        {
            for (int i = 0; i < System.Math.Ceiling(Convert.ToDouble(ViewBag.Entity.Count) / 4); i++)
            {
                <div class="row">
                    @for (int j = 0; j < 4; j++)
                {
                    if (i * 4 + j < ViewBag.Entity.Count)
                    {
                        <div class="col-md-3">
                            <div class="single-member effect-1" title="@ViewBag.Entity[i * 4 + j].Name">
                                <!-- 人物图片 -->
                                <div class="member-image">
                                    <img src="~/Images/人物图片/@ViewBag.Entity[i * 4 + j].Name-1.jpg" alt="Member">
                                </div>

                                <!-- 人物介绍 -->
                                <div class="member-info">
                                    <h2 style="margin-bottom:52px;">@ViewBag.Entity[i * 4 + j].Name</h2>
                                    @*<h4>EnglishName</h4>*@
                                    @{
                                        <p>@ViewBag.Entity[i * 4 + j].Introduction[0]</p>

                                    }            <div class="social-touch">
                                        @*<a class="fb-touch" href="#"></a>
                                        <a class="tweet-touch" href="#"></a>
                                        <a class="linkedin-touch" href="#"></a>*@
                                    </div>
                                </div>

                                <!-- 人物关系 -->
                                <div class="member-relation">
                                    @{
                                    if (ViewBag.Relation.ContainsKey(@ViewBag.Entity[i * 4 + j].Name))
                                    {
                                        foreach (string relation in ViewBag.Relation[@ViewBag.Entity[i * 4 + j].Name])
                                        {
                                            <span class="badge badge-pill badge-primary">@relation</span>
                                    }
                                }
                                    }
                                </div>
                            </div>
                        </div>
                }
                else { break; }
            }
                </div>
        }
    }
    else
    {
        <div class="errorpPage-box">
            <div class="errorpPage-img">
                <img src="~/Images/404.png">
            </div>
            <div class="errorpPage-tip">
                <h5>抱歉，暂未收录相关人物！</h5>
            </div>
        </div>
    }
        }



        <!-- 分页信息 -->
        @{
        if (ViewBag.Total > 0)
        {
            <div class="row">
                <div style="margin: 5rem auto 0 auto;max-width:100%;">
                    <ul class="pagination" style="float:left">
                        @{
                            int start;
                            if (ViewBag.Page <= 4) { start = 1; }
                            else if (ViewBag.Page + 3 > ViewBag.Count)
                            {
                                start = Convert.ToInt32(ViewBag.Count) - 6;
                                if (start < 0)
                                {
                                    start = 1;
                                }
                            }
                            else { start = ViewBag.Page - 3; }

                            if (ViewBag.Page > 1)
                            {
                                <li class="page-item"><a class="page-link" href="@Url.Action("Search", "Display", new { entity_name = ViewBag.Search, page = ViewBag.Page - 1})">上一页</a></li>
                            }

                            for (int i = start; i < start + 7; i++)
                            {
                                if (i > ViewBag.Count) { break; }
                                if (i == ViewBag.Page)
                                {
                                    <li class="page-item active"><a class="page-link" href="@Url.Action("Search", "Display", new { entity_name = ViewBag.Search, page = i})">@i</a></li>
                                }
                                else
                                {
                                    <li class="page-item"><a class="page-link" href="@Url.Action("Search", "Display", new { entity_name = ViewBag.Search, page = i})">@i</a></li>
                                }
                            }

                            if (ViewBag.Page < ViewBag.Count){<li class="page-item"><a class="page-link" href="@Url.Action("Search", "Display", new { entity_name = ViewBag.Search, page = ViewBag.Page + 1})">下一页</a></li>}
                         }
                    </ul>
                    <span style="float:left;color:#666;padding:.5rem .75rem"> 共<span>@ViewBag.Count</span>页</span>
                    <span style="float:left;color:#666;padding:.5rem .5rem;padding-left:0">到第</span>
                    <input id="page_search" value="@ViewBag.Page" style="height:40px;width:40px;text-align:center;border-radius:3px;border:1px solid #ddd;outline:none;float:left;" onkeyup="value=value.replace(/[^\d]/g,'')" />
                    <span style="float:left;color:#666;padding:.5rem .5rem">页</span>
                    <ul class="pagination" style="float:left;padding-left:0.5rem">
                        <li class="page-item"><a class="page-link" id="search">确定</a></li>
                    </ul>
                </div>
            </div>
    }
    else
    {

    }
        }

    </div>

@section scripts{
    <script>
    //重置搜索栏内容
    if ('@ViewBag.Search' == 'all')
        $("#input-number").val('');
    else
        $("#input-number").val('@ViewBag.Search');

    //
    $("#search").click(function () {
        target = $("#page_search").val();
        if (target >= 1 && target <= @ViewBag.Count && target != @ViewBag.Page) {
            window.location = "http://" + window.location.host + "/Display/Search/@ViewBag.Search/" + target
        }
    });

    //浏览人物详细信息
        $(".single-member").click(function () {
        window.location = "http://" + window.location.host + "/Display/Detail/" + $(this).attr("title");
    });

    //人物检索
    $("#peo-search").click(function () {
        if ($("#input-number").val() == "")
            window.location = "http://" + window.location.host + "/Display/Search/all";
        else
            window.location = "http://" + window.location.host + "/Display/Search/" + $("#input-number").val();
    });
    </script>
}